spring:
  datasource:
    name: test_db
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    pool:
      pool-name: TestDBHikariCP
      initial-pool-size: 5
      minimum-pool-size: 5
      maximum-pool-size: 20
      connection-timeout-ms: 60000
      idle-connection-check-interval-ms: 60000
      connection-idle-timeout-ms: 300000

logging:
  level:
    org.example.repository: debug # 你的项目包路径
    org.springframework: info
    org.mybatis: debug
    java.sql: debug # SQL语句和参数
    org.apache.ibatis: debug

mybatis:
  type-aliases-package: org.example.domain # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 添加日志配置
