spring:
  profiles:
    active:
      - postgresql

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: org.example.model.domain

# Spring日志配置
logging:
  level:
    org.springframework: info
    logging.level.org.springframework.aop: DEBUG # 开启 AOP 日志
    java.sql: debug # SQL语句和参数
    org.mybatis: debug
    org.apache.ibatis: debug
    org.example.mybatis: debug
    org.example.repository: debug # 设置包路径的日志级别为debug
