spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE_1}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

logging:
  level:
    org.example.repository: debug # 你的项目包路径
    org.springframework: info
    org.mybatis: debug
    java.sql: debug # SQL语句和参数
    org.apache.ibatis: debug

mybatis:
  type-aliases-package: org.example.domain # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 添加日志配置
