spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.1.12/testdb1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
    ds2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.1.12/testdb2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 解决启动时swagger报错
swagger:
  enabled: true
  title: spring-boot-mybatis-multids api document
  description: This is a restful api document of spring-boot-mybatis-multids.
  version: 1.0-SNAPSHOT
mybatis:
  config-location: classpath:mybatis-config.xml
# 分页插件配置：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  helper-dialect: mysql # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。
  reasonable: true # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
logging:
  config: classpath:logback-spring.xml
response:
  show-trace: true
