apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deploy-nginx
  name: my-deploy-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy-nginx
  template:
    metadata:
      labels:
        app: my-deploy-nginx
    spec:
      containers:
      - image: docker.io/nginx:1.23
        name: nginx