# kubectl run my-pod-nginx --image=docker.io/nginx:1.23 --port=80
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-pod-nginx
  name: my-pod-nginx
spec:
  containers:
  - image: docker.io/nginx:1.23
    name: my-pod-nginx
    ports:
    - containerPort: 80