# kubectl expose pod my-pod-nginx --target-port=80 --port=10080 --type=NodePort --name my-pod-nginx-svc
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: my-pod-nginx
  name: my-pod-nginx-svc
spec:
  ports:
  - port: 10080
    protocol: TCP
    targetPort: 80
  selector:
    run: my-pod-nginx
  type: NodePort
status:
  loadBalancer: {}