logging:
  request:
    use-custom-filter-exclude-paths: N
    # 配置不需要记录日志的路径
    exclude-paths:
      - "/actuator/**"
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
      - "/favicon.ico"
      - "/static/**"
      - "/resources/**"
      - "/webjars/**"
      - "/error"
      - "/health-check"
    # 配置慢请求阈值(毫秒)
    slow-request-threshold-ms: 5000

custom-filter:
  exclude-paths:
    - "/actuator/**"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - "/favicon.ico"
    - "/static/**"
    - "/resources/**"
    - "/webjars/**"
    - "/error"
    - "/health-check"
