spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_TEST_DB:postgres}?reWriteBatchedInserts=true&socketTimeout=30&connectTimeout=10
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池基本配置
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      # 验证查询
      connection-test-query: SELECT 1
      # 自动提交
      auto-commit: true
      # 连接初始化 SQL
      connection-init-sql: SET TIME ZONE 'UTC'
      # 验证超时时间
      validation-timeout: 5000
      # 允许连接池暂停
      allow-pool-suspension: false
      # 注册 JMX MBeans
      register-mbeans: true
