server:
  servlet:
    # 解决静态页面中文乱码
    encoding:
      enabled: true
      force: true
      charset: utf-8

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/E:/app/data/testdb
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 解决启动时swagger报错

#logging:
#  level:
#    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
#  # logging.file.path 和 logging.file.name 同时存在时，只有 logging.file.name 生效
#  file:
#    path: E:\logs # 日志文件名缺省值spring.log
#    name: application.log

swagger:
  enabled: true
  title: spring-boot-demo
  description: spring-boot-demo
  version: 1.0-SNAPSHOT

SFID:
  datacenterId: 2
  workerId: 2
