## 配置用户名和密码方式一
#spring:
#  security:
#    user:
#      name: admin
#      password: 12345

spring:
  profiles:
    include: h2,mybatis-plus
  thymeleaf:
    # 静态资源热部署
    cache: false
  redis:
    host: 192.168.1.22
    port: 6379

app:
  sso:
    enabled: false