spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  enabled: true
  title: @artifactId@
  description: @description@
  version: @version@

inbound-channel-adapter-fixed-rate: 3605000
inbound-channel-adapter-cron: 0/5 * 1 * * ?

external-system:
  example:
    env:
      sit: http://localhost:8080/example/sit
      uat: http://localhost:8080/example/uat
