spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  enabled: true
  title: @artifactId@
  description: @description@
  version: @version@

external-system:
  example:
    env:
      sit: http://localhost:8080/example/sit
      uat: http://localhost:8080/example/uat
