spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api

#springdoc:
#  api-docs:
#    version: openapi_3_0  # 可选值: openapi_3_0, openapi_3_1
#    path: /v3/api-docs # 默认是/v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operationsSorter: method