spring:
  profiles:
    active:
      - postgresql

mybatis-plus:
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: org.example.model.domain

# Spring日志配置
logging:
  level:
    org.springframework: info
    logging.level.org.springframework.aop: DEBUG # 开启 AOP 日志
    java.sql: debug # SQL语句和参数
    org.hibernate.type.descriptor.sql.BasicBinder: trace # 显示SQL参数
    org.mybatis: debug
    org.apache.ibatis: debug
    com.baomidou.mybatisplus: debug
    org.example.mapper: debug # 设置包路径的日志级别为debug