@startuml
'https://plantuml.com/class-diagram

' 依赖关系
动物 ..> 氧气
动物 ..> 水

'组合关系（合成关系）
翅膀 <--* 鸟

'聚合关系
雁群 o-- 大雁

interface 飞翔{
}

abstract class 动物{
}

abstract class 鸟 extends 动物{
}

class 大雁 extends 鸟 implements 飞翔{
}

class 鸭 extends 鸟{
}

class 企鹅 extends 鸟{
}


@enduml