@startuml
'https://plantuml.com/class-diagram

Director o-- Builder

class Product{
}

interface Builder{
buildPartA()
buildPartB()
buildPartC()
Product getProduct()
}

class ConcreteBuilder1 implements Builder{
}

class ConcreteBuilder2 implements Builder{
}

class Director{
+ construct()
}

@enduml
