@host = http://localhost:8080

# 用户管理 API 文档

### 获取用户列表1
POST {{host}}/users/list
Content-Type: application/json

{
    "sorting": [
        {
            "field": "createAt",
            "sort": "desc"
        }
    ],
    "current": 1,
    "size": 5
}

### 获取用户列表2
POST {{host}}/users/list
Content-Type: application/json

{
    "isDeleted": false,
    "sorting": [
        {
            "field": "createAt",
            "sort": "desc"
        }
    ],
    "current": 1,
    "size": 5
}

### 获取用户列表3
POST {{host}}/users/list
Content-Type: application/json

{
    "isEnabled": true,
    "isDeleted": false,
    "sorting": [
        {
            "field": "createAt",
            "sort": "desc"
        }
    ],
    "current": 1,
    "size": 5
}

### 获取用户列表4
POST {{host}}/users/list
Content-Type: application/json

{
    "username": "chen",
    "firstName": "Tom",
    "lastName": "Mai",
    "isEnabled": true,
    "isDeleted": false,
    "sorting": [
        {
            "field": "createAt",
            "sort": "desc"
        }
    ],
    "current": 1,
    "size": 5
}



### 获取用户详情
GET {{host}}/users/2025053112024864700001


### 创建用户
POST {{host}}/users
Content-Type: application/json

{
    "username": "tracychen",
    "firstName": "tracy",
    "lastName": "Chen",
    "password": "encrypted_password"
}


### 更新用户
PUT {{host}}/users
Content-Type: application/json

{
    "id": "2025060216252256200001",
    "isEnabled": false
}


### 删除用户
DELETE {{host}}/users/2025060216252256200001