@host = http://localhost:8080

# 用户管理 API 文档

### 获取用户列表
POST {{host}}/users/list
Content-Type: application/json

{
    "username": "chen",
    "sorting": [
        {
            "field": "createAt",
            "sort": "desc"
        }
    ],
    "current": 1,
    "size": 5
}



### 获取用户详情
GET {{host}}/users/2025053111191108200001


### 创建用户
POST {{host}}/users
Content-Type: application/json

{
    "username": "tracychen",
    "firstName": "tracy",
    "lastName": "Chen",
    "password": "encrypted_password"
}


### 更新用户
PUT {{host}}/users
Content-Type: application/json

{
    "id": "2025053111191108200001",
    "password": "encrypted_password_test"
}


### 删除用户
DELETE {{host}}/users/2025053111191108200001