@host = http://localhost:8080

# Concrete Domains API 文档


### List
POST {{host}}/concrete-domains/list
Content-Type: application/json

{
}


### Get
GET {{host}}/concrete-domains/2025061615053846100009


### Create
POST {{host}}/concrete-domains
Content-Type: application/json

{
  "data":{
    "integers":[
      1,
      2,
      3
    ],
    "longs":[
      1000000000001,
      1000000000002,
      1000000000003
    ],
    "bigDecimals": [
      "2025061615043403900001",
      "2025061615043403900002",
      "2025061615043403900003"
    ],
    "strings": [
      "string1",
      "string2",
      "string3"
    ]
  }
}


### Update
PUT {{host}}/concrete-domains
Content-Type: application/json

{

}


### Delete
DELETE {{host}}/concrete-domains/2025061513304855800002
