@host = http://localhost:8080

# Concrete Domains API 文档


### List
POST {{host}}/concrete-domains/list
Content-Type: application/json

{
}


### Get
GET {{host}}/concrete-domains/2025061621573938200002


### Create
POST {{host}}/concrete-domains
Content-Type: application/json

{
  "data":{
    "integers":[
      1,
      2,
      3
    ],
    "longs":[
      1000000000001,
      1000000000002,
      1000000000003
    ],
    "bigDecimals": [
      "2025061615043403900001",
      "2025061615043403900002",
      "2025061615043403900003"
    ],
    "strings": [
      "string1",
      "string2",
      "string3"
    ],
    "concreteElementA":{
      "id": "2025061615053846100009",
      "name": "Element A",
      "description": "This is a concrete element A"
    },
    "concreteElementAList": [
      {
        "id": "2025061615053846100009",
        "name": "Element A1",
        "description": "This is a concrete element A1"
      },
      {
        "id": "2025061615053846100010",
        "name": "Element A2",
        "description": "This is a concrete element A2"
      }
    ],
    "concreteElementB":{
      "id": "2025061615053846100011",
      "name": "Element B",
      "description": "This is a concrete element B"
    },
    "concreteElementBList": [
      {
        "id": "2025061615053846100011",
        "name": "Element B1",
        "description": "This is a concrete element B1"
      },
      {
        "id": "2025061615053846100012",
        "name": "Element B2",
        "description": "This is a concrete element B2"
      }
    ]
  }
}


### Update
PUT {{host}}/concrete-domains
Content-Type: application/json

{

}


### Delete
DELETE {{host}}/concrete-domains/2025061513304855800002
