@host = http://localhost:8080

# JSONB TEST API 文档


### List
GET {{host}}/jsonb


### Get
GET {{host}}/jsonb/2025061507344746600005


### Create
POST {{host}}/jsonb
Content-Type: application/json

{
    "stringData": "{\"name\":\"John Doe\",\"contact\":{\"address\":\"New York\",\"phone\":\"1234567890\"},\"tags\":[\"Important\",\"Urgent\",\"Review\"],\"level1\":{\"level2\":{\"value\":\"test\"}},\"items\":[{\"name\":\"Product1\",\"price\":100},{\"name\":\"Product2\",\"price\":200}]}",
    "personData": {
        "name": "John Doe",
        "contact": {
            "address": "New York",
            "phone": "1234567890"
        },
        "tags": ["Important", "Urgent", "Review"],
        "level1": {
            "level2": {
                "value": "test"
            }
        },
        "items": [
            {
                "name": "Product1",
                "price": 100
            },
            {
                "name": "Product2",
                "price": 200
            }
        ]
    }
}


### Update
PUT {{host}}/jsonb
Content-Type: application/json

{
    "id": "2025061410465014500011",
    "stringData": "test update"
}


### Delete
DELETE {{host}}/jsonb/2025061507314340200004