@host = http://localhost:8080

# 产品管理 API 文档


### 获取产品列表
POST {{host}}/products/list
Content-Type: application/json

{
	"data": {
		"filter": {
			"productName": "iPhone"
		},
		"sort": [{
				"name": "createAt",
				"direction": "desc"
			}],
		"page": {
			"current": 1,
			"size": 5
		}
	}
}


### 获取产品详情
GET {{host}}/products/2025060710400222400001


### 创建产品
POST {{host}}/products
Content-Type: application/json

{
    "productName": "iPhone 13 x",
    "price": "899.99",
    "stockQuantity": 100,
    "description": "iPhone x",
    "tags": "[\"phone\", \"apple\", \"5G\"]",
    "status": "IN_STOCK",
    "properties": "{\"color\": \"black\", \"storage\": \"128GB\"}",
    "searchVector": "phone apple mobile"
}


### 更新产品
PUT {{host}}/products
Content-Type: application/json

{
    "id": "2025061014034510200002",
    "stockQuantity": 100,
    "isActive": false
}


### 删除产品
DELETE {{host}}/products/2025061014034510200002