server:
  servlet:
    # 解决静态页面中文乱码
    encoding:
      enabled: true
      force: true
      charset: utf-8
spring:
  profiles:
    include: h2,mybatis-plus,swagger
logging:
  config: classpath:logback-spring.xml
response:
  show-trace: true
