spring:
  application:
    name: spring-boot-study
    group: spring
  profiles:
    active: dev

# https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging
logging:
  include-application-name: false
  include-application-group: false
  config: classpath:logback-spring.xml # Custom Log Configuration
  file:
    path: logs
