apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
spec:
  ports:
  - port: 10080     # service暴露出来的port，在其他pod内可以通过serviceIp:port或者serviceName.namespace.svc:port访问，用于集群内访问
    protocol: TCP
    targetPort: 80  # container暴露出来的port，同一个pod中，不同container之间可以互相访问
    nodePort: 30080 # 与type: NodePort一起使用
  type: NodePort    # type设置为NodePort，就可以让外网访问了
  selector:
    run: my-nginx   # 通过selector来寻找相同label的pod