server:
  port: 8080

logging:
  level:
    org.springframework.web: debug
    org.springframework.web.cors: debug

cors:
  # 全局 CORS 配置
  global:
    # 允许的源，使用列表形式
    allowed-origins:
      #- "*"    # 生产环境建议替换为具体的域名
      - "http://localhost:6060/"
    # 允许的 HTTP 方法
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    # 允许的请求头
    allowed-headers:
      - "*"
    # 是否允许发送 cookie
    allow-credentials: false
    # 预检请求的缓存时间（秒）
    max-age: 3600
    # Spring 6.x 特定配置
    allowed-origin-patterns:
      #- "*"    # 生产环境建议替换为具体的模式，如 "https://*.example.com"
      - "http://localhost:6060/"

# 应用程序配置
spring:
  mvc:
    cors:
      # 是否启用 Spring MVC 的 CORS 支持
      enabled: true
