spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      schema-locations: classpath*:scripts/schema.sql
      data-locations: classpath*:scripts/data.sql
