spring:
  datasource:
    driver-class-name: org.h2.Driver
    # 连接内存数据库，表名和字段名区分大小写，语法：jdbc:h2:mem:<databaseName>;database_to_upper=false
    url: jdbc:h2:mem:test;database_to_upper=false
    username: sa
    password: 123
  # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  sql:
    init:
      schema-locations: classpath*:scripts/schema.sql
      data-locations: classpath*:scripts/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springfox:
  enabled: true
  documentation:
    swagger-ui:
      enabled: true
      title: JdbcTemplate Api Document
      description: This is a restful api document of JdbcTemplate.
      version: 1.0.0