spring:
  datasource:
    driver-class-name: org.h2.Driver
    # 嵌入式(本地)连接方式连接H2数据库，语法：jdbc:h2:[file:][<path>]<databaseName>
    # 表名和字段名区分大小写，语法：jdbc:h2:[file:][<path>]<databaseName>;database_to_upper=false
    url: jdbc:h2:file:E:/app/data/test;database_to_upper=false
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springfox:
  enabled: true
  documentation:
    swagger-ui:
      enabled: true
      title: JdbcTemplate Api Document
      description: This is a restful api document of JdbcTemplate.
      version: 1.0.0