spring:
  datasource:
    driver-class-name: org.h2.Driver
    # 设置表名和字段名区分大小写 ;database_to_upper=false
    # url: jdbc:h2:mem:test;database_to_upper=false
    url: jdbc:h2:file:E:/app/data/test;database_to_upper=false
    username: sa
    password: 123
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springfox:
  enabled: true
  documentation:
    swagger-ui:
      enabled: true
      title: JdbcTemplate Api Document
      description: This is a restful api document of JdbcTemplate.
      version: 1.0.0


#logging:
#  level:
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG