server:
  port: 8080

spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# /swagger-ui/index.html
springfox:
  enabled: true
  documentation:
    swagger-ui:
      enabled: true
      title: Spring Cloud OpenFeign Api Document
      description: This is a restful api document of Spring Cloud OpenFeign.
      version: 1.0-SNAPSHOT


# openfeign
feign:
  client:
    config:
      users-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        requestInterceptors:
          - cn.maiaimei.example.interceptor.FeignClientLoggingRequestInterceptor
#logging:
#  level:
#    cn.maiaimei.example.client.UserClient: DEBUG
