# /swagger-ui/index.html
spring:
  mvc:
    pathmatch:
      # 解决启动时swagger报错
      matching-strategy: ant_path_matcher

springfox:
  enabled: true
  documentation:
    swagger-ui:
      enabled: true
      title: spring-boot-validation
      description: This is a restful api document of spring-boot-validation.
      version: 1.0.0