spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.1.12/testdb1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: root
      password: 123456

java-model:
  target-package: cn.maiaimei.example.pojo.entity
  target-project: .\src\main\java
java-client:
  target-package: cn.maiaimei.example.mapper
  target-project: .\src\main\java
sql-map:
  target-package: cn.maiaimei.example.mapper
  target-project: .\src\main\resources
